apps/cms/urls.py
from django.urls import path
from . import views, course_views,staff_views

app_name = 'cms'
urlpatterns = [
    path('', views.index, name='index'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('edit_news/', views.EditNews.as_view(), name='edit_news'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('banners/', views.banners, name='banners'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('add_banner/', views.add_banners, name='add_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
]
# 课程相关的url映射
urlpatterns += [
    path('pub_course/', course_views.PubCourse.as_view(), name='pub_course'),
]

# 员工管理
urlpatterns+=[
    path('staffs',staff_views.staffs_view,name='staffs'),
    path('add_staffs/',staff_views.AddStaffView.as_view(),name='add_staffs'),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('list/', views.news_list, name='news_list'),
    path('public_comment/', views.public_comment, name='public_comment'),
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'  # 注册app的url
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('register/', views.register, name='register'),
    path('cache/', views.test, name='cache'),
]

xfz/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('admin/', admin.site.urls),
    path('ueditor/', include('apps.ueditor.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path("favicon.ico", RedirectView.as_view(url='static/favicon.ico')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT[0])

apps/cms/models.py
from django.db import models


# Create your models here.
class NewsCategory(models.Model):
    name = models.CharField(max_length=100)

apps/course/models.py
from django.db import models


class CourseCategory(models.Model):
    name = models.CharField(max_length=100)


class Teacher(models.Model):
    username = models.CharField(max_length=100)
    avatar = models.URLField()
    jobtitle = models.CharField(max_length=100)
    profile = models.TextField()


class Course(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey('CourseCategory', on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey('Teacher', on_delete=models.DO_NOTHING)
    video_url = models.URLField()
    cover_url = models.URLField()
    price = models.FloatField()
    duration = models.IntegerField()
    profile = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)

apps/news/models.py
from django.db import models


# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('cms.NewsCategory', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)

    # 按时间倒序排序
    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey('news.News', on_delete=models.CASCADE, related_name='comments')
    # 级联删除，即新闻被删除，它关联的评论也会被删除;related_name是通过news访问所有评论时，可通过comments访问
    author = models.ForeignKey('xfzauth.User', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority']

apps/cms/forms.py
from apps.forms import FormMixin
from django import forms
from apps.news.models import News, Banner
from apps.course.models import Course, CourseCategory


class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField(error_messages={'required': '必须传入分类的ID！'})  # 主键
    name = forms.CharField(max_length=100)


class WriteNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']


class EditNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()
    news_id = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']


class AddBannerForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banner
        fields = ['priority', 'link_to', 'image_url']


class CourseForm(forms.ModelForm, FormMixin):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()

    class Meta:
        model = Course
        exclude = ('teacher', 'category')

apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views import View
from django.views.decorators.http import require_POST, require_GET
from .models import NewsCategory
from utils import restful
from .forms import EditNewsCategoryForm, WriteNewsForm, AddBannerForm, EditNewsForm
import os
from django.conf import settings
from apps.news.models import News, Banner
from apps.news.serializer import BannerSerializer
from django.core.paginator import Paginator
from datetime import datetime
from django.utils.timezone import make_aware
from urllib import parse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required


# Create your views here.
# 该装饰器保证了只有公司员工可以使用该视图函数，login_url制定了非公司员工重定向的页面
@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')


# 不分页显示所有分类和新闻
# def news_list(request):
#     context = {
#         'categories': NewsCategory.objects.all(),
#         'newses': News.objects.select_related('category', 'author').all()
#     }
#     return render(request, 'cms/news_list.html', context=context)

# 实现分页算法
@method_decorator(permission_required(perm='news.change_news', login_url='/'), name='dispatch')
class NewsListView(View):
    def get(self, request):
        page = int(request.GET.get('p', 1))

        newses = News.objects.select_related('category', 'author')  # select_related查询到的是QuerySet对象

        start = request.GET.get('start')  # 字符串
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0) or 0)

        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')  # 字符串转化成标准时间
            else:
                start_date = datetime(year=2021, month=1, day=1)
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))

        if title:
            newses = newses.filter(title__icontains=title)  # icontains表示大小写不敏感
        if category_id:
            newses = newses.filter(category=category_id)

        paginator = Paginator(newses, 2)  # 第一个参数是可迭代对象，2表示每页显示的元素数量
        page_obj = paginator.page(page)  # 获取page对象

        page_info = self.get_pagination_data(paginator, page_obj)
        context = {
            'categories': NewsCategory.objects.all(),
            'newses': page_obj.object_list,  # 获得包含所有当前页对象的列表
            'page_obj': page_obj,
            'paginator': paginator,
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&' + parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or '',
            })
        }
        context.update(page_info)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_mount=2):
        left_has_more = False
        right_has_more = False

        current_page = page_obj.number  # 获取当前页码
        num_pages = paginator.num_pages  # 获取总页数

        if current_page - around_mount >= 3:
            left_has_more = True
            left_pages = range(current_page - around_mount, current_page)
        else:
            left_pages = range(1, current_page)
        if current_page + around_mount < num_pages - 1:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_mount + 1)
        else:
            right_pages = range(current_page + 1, num_pages + 1)
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'current_page': current_page,
            'num_pages': num_pages
        }


@method_decorator(permission_required(perm='news.change_news', login_url='/'), name='dispatch')
class EditNews(View):
    def get(self, request):
        new_id = request.GET.get('news_id')
        news = News.objects.get(id=new_id)
        categories = NewsCategory.objects.all()
        context = {
            'news': news,
            'categories': categories,
        }
        return render(request, 'cms/write_news.html', context)

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            news_id = form.cleaned_data.get('news_id')
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.filter(id=news_id).update(title=title, desc=desc, thumbnail=thumbnail, content=content)
            return restful.OK()
        else:
            return restful.params_errors(message=form.get_errors())


@method_decorator(permission_required(perm='news.change_news', login_url='/'), name='dispatch')
class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {'categories': categories}
        return render(request, 'cms/write_news.html', context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category,
                                author=request.user)
            return restful.OK()
        else:
            return restful.params_errors(message=form.get_errors())


@require_POST
@permission_required(perm='news.delete_news', login_url='/')
def delete_news(request):
    news_id = request.POST.get('news_id')
    try:
        news_rs = News.objects.filter(id=news_id)
        if news_rs.exists():
            thumbnail = news_rs.first().thumbnail
            thumbnail_path = os.path.join(settings.MEDIA_ROOT[0], thumbnail.split('/')[-1])
            try:
                os.remove(thumbnail_path)
                return restful.OK()
            except OSError:
                return restful.params_errors(message='不能删除目录！')
            except:
                return restful.params_errors(message='删除文件失败')
            finally:
                news_rs.delete()
    except Exception as e:
        return restful.params_errors(message=e)


@require_GET
@permission_required(perm='news.add_newscategory', login_url='/')
def news_category(request):
    categories = NewsCategory.objects.all()
    categories_num = len(categories)
    context = {'categories': categories, 'categories_num': categories_num}
    return render(request, 'cms/news_category.html', context=context)


@require_POST
@permission_required(perm='news.add_newscategory', login_url='/')
def add_news_category(request):
    name = request.POST.get('name')
    exist = NewsCategory.objects.filter(name=name).exists()
    if not exist:
        NewsCategory.objects.create(name=name)
        return restful.OK()
    else:
        return restful.params_errors(message='该分类已存在！')


@require_POST
@permission_required(perm='news.change_newscategory', login_url='/')
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(id=pk).update(name=name)  # id和pk是一样的,都是指主键，其他不是
            return restful.OK()
        except:
            return restful.params_errors(message='该分类不存在！')
    else:
        errors = form.get_errors()
        return restful.params_errors(message=errors)


@require_POST
@permission_required(perm='news.delete_newscategory', login_url='/')
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.OK()
    except:
        return restful.unauth(message='该分类不存在！')


@require_POST
@staff_member_required(login_url='/')
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    if os.path.exists(os.path.join(settings.MEDIA_ROOT[0], name)):
        return restful.params_errors(message='该文件已存在！请修改文件名重新上传！')
    with open(os.path.join(settings.MEDIA_ROOT[0], name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)  # 该方法已写好了网站所在的地址和端口（现在是localhost:8000）
    # 参数即需要补充的文件相对路径
    return restful.result(data={'url': url})


@permission_required(perm='news.add_banner', login_url='/')
def banners(request):
    return render(request, 'cms/banners.html')


@permission_required(perm='news.add_banner', login_url='/')
def banner_list(request):
    banner_query = Banner.objects.all()  # 返回的是query对象，故需要使many=True
    serilize = BannerSerializer(banner_query, many=True)
    print("序列化后的banner：", serilize.data)
    return restful.result(data=serilize.data)


@permission_required(perm='news.add_banner', login_url='/')
def add_banners(request):
    form = AddBannerForm(request.POST)
    if form.is_valid():
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!--    将http资源升级为https-->
<!--    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}首页{% endblock %} | 后台管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="/static/images/photo.jpg"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">张猛</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="/static/images/photo.jpg"
                                     class="img-circle" alt="User Image">
                                <p>
                                    {{user.username}}
                                    <small>python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'xfzauth:logout' %}" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                {% if perms.news.change_news %}
                <li class="header">新闻管理</li>
                <li>
                    <a href="{% url 'cms:news_list' %}">
                        <i class="fa fa-list"></i>
                        <span>新闻列表</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:write_news' %}">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:news_category' %}">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:banners' %}">
                        <i class="fa fa-window-restore"></i>
                        <span>轮播图</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.course.change_course %}
                <li class="header">课程管理</li>
                <li>
                    <a href="{% url 'cms:pub_course' %}">
                        <i class="fa fa-tv"></i>
                        <span>发布课程</span>
                    </a>
                </li>
                {% endif %}
                {% if user.is_superuser %}
                <li class="header">员工管理</li>
                <li>
                    <a href="{% url 'cms:staffs' %}">
                        <i class="fa fa-group"></i>
                        <span>员工管理</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <footer class="main-footer">
        <strong>CMS</strong>后台管理系统
    </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>欢迎来到CMS管理系统</h1>
{% endblock %}

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}
{% load news_filters %}

{% block title %}
    新闻列表
{% endblock %}

{% block head %}
    <style>
    .left-group{
        margin-right: 20px;
    }
    </style>
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻列表管理</h1>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <form action="" method="get" class="form-inline">
                <div class="form-group left-group">
                    <label for="">时间：</label>
                    {% if start %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly value="{{ start }}">
                    {% else %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly>
                    {% endif %}
                    <span>—</span>
                    {% if end %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly value="{{ end }}">
                    {% else %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly>
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="title-input">标题：</label>
                    {% if title %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字" value="{{ title }}">
                    {% else %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字">
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="category-input">分类：</label>
                    <select name="category" id="" class="form-control">
                        {% if category_id == 0 %}
                            <option value="0" selected>所有分类</option>
                        {% else %}
                            <option value="0">所有分类</option>
                        {% endif %}
                        {% for category in categories %}
                            {% if category_id == category.pk %}
                                <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                            {% else %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group left-group">
                    <button class="btn btn-primary">查询</button>
                </div>
                <div class="form-group">
                    <a href="{% url 'cms:news_list' %}">清除查询</a>
                </div>
            </form>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>标题</th>
                        <th>分类</th>
                        <th>发布时间</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for news in newses %}
                        <tr>
                            <td><a target="_blank" href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a></td>
                            <td>{{ news.category.name }}</td>
                            <td>{{ news.pub_time|time_format }}</td>
                            <td>{{ news.author.username }}</td>
                            <td>
                                <a href="{% url 'cms:edit_news' %}?news_id={{ news.pk }}" class="btn btn-info btn-xs">编辑</a>
                                <button class="btn btn-danger btn-xs delete-btn" data-news-id="{{ news.pk }}">删除</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="box-footer">
            <p class="pull-left">第{{ current_page }}/总共{{ num_pages }}页</p>
            <ul class="pagination pull-right">
                {#上一页#}
                {% if page_obj.has_previous %}
                    <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                {% endif %}

                {# 是否需要出现三个点 #}
                {% if left_has_more %}
                    <li><a href="?p=1">1</a></li>
                    <li><a href="javascript:void(0);">...</a></li>
                {% endif %}

                {# 左边的页码 #}
                {% for left_page in left_pages %}
                    <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                {% endfor %}

                {# 当前的页面 #}
                <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                {# 右边的页码 #}
                {% for right_page in right_pages %}
                    <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                {% endfor %}

                {# 用来控制右边三个点 #}
                {% if right_has_more %}
                    <li><a href="javascript:void(0);">...</a></li>
                    <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                {% endif %}

                {#下一页#}
                {% if page_obj.has_next %}
                    <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
</div>
{% endblock %}

400 700 3030
400 699 3030

front/templates/cms/staff.html
{% extends 'cms/base.html' %}
{% block title %}员工管理{% endblock %}

{% block head %} {% endblock %}

{% block content-header %}
<h1>员工管理</h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="box-header">
            <a href="{% url 'cms:add_staffs' %}" class="btn btn-primary pull-right">添加员工</a>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>用户名</th>
                    <th>手机号</th>
                    <th>所属分组</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for staff in staffs %}
                    <tr>
                        <td>{{staff.username}}</td>
                        <td>{{staff.telephone}}</td>
                        <td>
                            {% if staff.is_superuser %}
                                超级管理员
                            {% endif %}
                            {% for group in staff.groups.all %}
                                {{group.name}}/
                            {% endfor %}
                        </td>
                        <td>
                            <button class="btn btn-info btn-xs">编辑</button>
                            <button class="btn btn-danger btn-xs">删除</button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="box-footer"></div>
    </div>
</div>
{% endblock %}