apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = 'payinfo'

urlpatterns = [
    path('', views.index, name='index'),
    path('download/',views.download,name='download'),
]

xfz/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('admin/', admin.site.urls),
    path('ueditor/', include('apps.ueditor.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path("favicon.ico", RedirectView.as_view(url='static/favicon.ico')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT[0])

apps/payinfo/models.py
from django.db import models
from shortuuidfield import ShortUUIDField


class PayInfo(models.Model):
    title = models.CharField(max_length=100)
    profile = models.CharField(max_length=200)
    price = models.FloatField()
    path = models.FilePathField()

apps/payinfo/views.py
from django.shortcuts import render
from .models import PayInfo
import os
from django.conf import settings
from django.http import FileResponse, Http404


def index(request):
    payinfos = PayInfo.objects.all()
    context = {
        'payinfos': payinfos,
    }
    return render(request, 'payinfo/payinfo.html', context=context)


def download(request):
    payinfo_id = request.GET.get('payinfo_id')
    payinfo = PayInfo.objects.filter(pk=payinfo_id).first()
    if payinfo:
        path = payinfo.path
        fp = open(os.path.join(settings.MEDIA_ROOT[0], path), 'rb')
        response = FileResponse(fp)
        response['Content-Type'] = 'image/jpeg'
        response['Content-Disposition'] = 'attachment;filename="%s"' % path.split('/')[-1]  # 以附件的形式下载，同时指定文件名称
        return response
    else:
        return Http404()

front/templates/payinfo/payinfo.html
{% extends 'base/base.html' %}
{% block title %}
    付费详情
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/payinfo/payinfo.min.css' %}">
{% endblock %}

{% block main %}
     <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="advertise-group">
                    <a href="#">
                        <img src="http://www.xfz.cn/static/build/images/web-venture-banner.png" alt="">
                    </a>
                </div>
                <ul class="document-list">
                    {% for payinfo in payinfos %}
                    <li>
                        <a href="{% url 'payinfo:download' %}?payinfo_id={{payinfo.pk}}">
                        <div class="category-group"
                             style="background-image:url('http://xfz.cn/static/build/images/web-bp-pc.png');"></div>
                        <div class="document-info">
                            <p class="document-title">{{payinfo.title}}</p>
                            <p class="document-desc">{{payinfo.profile}}</p>
                            <p class="document-price">￥{{payinfo.price}}</p>
                        </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}